import { IStudent } from './../models/student';

export const students: IStudent[] = [
  {
    id: 1,
    firstName: 'John',
    middleName: 'Michael',
    grandParentName: 'David',
    lastName: 'Smith',
    countryCode: 'US',
    phoneNumber: '5551234567',
    dateOfBirth: new Date('2005-01-15T00:00:00Z'),
    socialSecurity: '123-45-6789',
    identificationType: 1,
    identificationTypeText: 1,
    identificationNumber: 'A1234567',
    createdBy: 'admin',
    createdOn: new Date('2023-09-15T10:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-16T12:00:00Z'),
    isActive: true,
    notes: 'Excels in mathematics.',
    citizenShip: 'USA',
    gender: 1,
    genderText: 'Male',
    motherName: 'Susan',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 1,
    religionText: 'Christianity',
    placeOfBirth: 'Chicago, IL',
    gradeId: 1,
    gradeLabel: 'PG',
  },
  {
    id: 2,
    firstName: 'Jane',
    middleName: 'Elizabeth',
    grandParentName: 'George',
    lastName: 'Doe',
    countryCode: 'US',
    phoneNumber: '5559876543',
    dateOfBirth: new Date('2007-03-22T00:00:00Z'),
    socialSecurity: '987-65-4321',
    identificationType: 2,
    identificationTypeText: 2,
    identificationNumber: 'B2345678',
    createdBy: 'admin',
    createdOn: new Date('2023-09-10T14:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-11T16:00:00Z'),
    isActive: true,
    notes: 'Excellent in arts.',
    citizenShip: 'USA',
    gender: 2,
    genderText: 'Female',
    motherName: 'Laura',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 2,
    religionText: 'Islam',
    placeOfBirth: 'New York, NY',
    gradeId: 2,
    gradeLabel: 'KG',
  },
  {
    id: 3,
    firstName: 'Michael',
    middleName: 'James',
    grandParentName: 'Thomas',
    lastName: 'Johnson',
    countryCode: 'US',
    phoneNumber: '5555671234',
    dateOfBirth: new Date('2009-05-10T00:00:00Z'),
    socialSecurity: '456-78-9123',
    identificationType: 1,
    identificationTypeText: 1,
    identificationNumber: 'C3456789',
    createdBy: 'admin',
    createdOn: new Date('2023-09-12T08:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-12T09:00:00Z'),
    isActive: true,
    notes: 'Good in science.',
    citizenShip: 'USA',
    gender: 1,
    genderText: 'Male',
    motherName: 'Emily',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 3,
    religionText: 'Islam',
    placeOfBirth: 'Los Angeles, CA',
    gradeId: 3,
    gradeLabel: '1',
  },
  {
    id: 4,
    firstName: 'Olivia',
    middleName: 'Grace',
    grandParentName: 'Henry',
    lastName: 'Brown',
    countryCode: 'US',
    phoneNumber: '5552345678',
    dateOfBirth: new Date('2008-08-30T00:00:00Z'),
    socialSecurity: '321-65-9876',
    identificationType: 2,
    identificationTypeText: 2,
    identificationNumber: 'D4567890',
    createdBy: 'admin',
    createdOn: new Date('2023-09-18T13:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-18T14:00:00Z'),
    isActive: true,
    notes: 'Participates in drama.',
    citizenShip: 'USA',
    gender: 2,
    genderText: 'Female',
    motherName: 'Sarah',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 1,
    religionText: 'Christianity',
    placeOfBirth: 'Miami, FL',
    gradeId: 4,
    gradeLabel: '2',
  },
  {
    id: 5,
    firstName: 'Liam',
    middleName: 'Alexander',
    grandParentName: 'Edward',
    lastName: 'Davis',
    countryCode: 'US',
    phoneNumber: '5558765432',
    dateOfBirth: new Date('2010-02-15T00:00:00Z'),
    socialSecurity: '654-32-1987',
    identificationType: 1,
    identificationTypeText: 1,
    identificationNumber: 'E5678901',
    createdBy: 'admin',
    createdOn: new Date('2023-09-07T11:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-08T12:00:00Z'),
    isActive: true,
    notes: 'Loves sports.',
    citizenShip: 'USA',
    gender: 1,
    genderText: 'Male',
    motherName: 'Hannah',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 2,
    religionText: 'Islam',
    placeOfBirth: 'Houston, TX',
    gradeId: 5,
    gradeLabel: '3',
  },
  {
    id: 6,
    firstName: 'Emma',
    middleName: 'Sophia',
    grandParentName: 'Paul',
    lastName: 'Miller',
    countryCode: 'US',
    phoneNumber: '5554321765',
    dateOfBirth: new Date('2006-06-25T00:00:00Z'),
    socialSecurity: '123-65-4321',
    identificationType: 1,
    identificationTypeText: 1,
    identificationNumber: 'F6789012',
    createdBy: 'admin',
    createdOn: new Date('2023-09-15T10:30:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-16T11:30:00Z'),
    isActive: true,
    notes: 'Talented in music.',
    citizenShip: 'USA',
    gender: 2,
    genderText: 'Female',
    motherName: 'Isabella',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 1,
    religionText: 'Christianity',
    placeOfBirth: 'Phoenix, AZ',
    gradeId: 6,
    gradeLabel: '4',
  },
  {
    id: 7,
    firstName: 'Ethan',
    middleName: 'Gabriel',
    grandParentName: 'Charles',
    lastName: 'Wilson',
    countryCode: 'US',
    phoneNumber: '5553219876',
    dateOfBirth: new Date('2008-11-10T00:00:00Z'),
    socialSecurity: '789-65-4321',
    identificationType: 2,
    identificationTypeText: 2,
    identificationNumber: 'G7890123',
    createdBy: 'admin',
    createdOn: new Date('2023-09-18T14:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-18T15:00:00Z'),
    isActive: true,
    notes: 'Top performer in science.',
    citizenShip: 'USA',
    gender: 1,
    genderText: 'Male',
    motherName: 'Linda',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 2,
    religionText: 'Islam',
    placeOfBirth: 'Austin, TX',
    gradeId: 7,
    gradeLabel: '5',
  },
  {
    id: 8,
    firstName: 'Sophia',
    middleName: 'Olivia',
    grandParentName: 'Joseph',
    lastName: 'Martinez',
    countryCode: 'US',
    phoneNumber: '5558763219',
    dateOfBirth: new Date('2007-07-04T00:00:00Z'),
    socialSecurity: '432-21-8765',
    identificationType: 1,
    identificationTypeText: 1,
    identificationNumber: 'H8901234',
    createdBy: 'admin',
    createdOn: new Date('2023-09-09T13:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-09T14:00:00Z'),
    isActive: true,
    notes: 'Excellent at literature.',
    citizenShip: 'USA',
    gender: 2,
    genderText: 'Female',
    motherName: 'Maria',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 1,
    religionText: 'Christianity',
    placeOfBirth: 'San Diego, CA',
    gradeId: 8,
    gradeLabel: '6',
  },
  {
    id: 9,
    firstName: 'Daniel',
    middleName: 'Thomas',
    grandParentName: 'Frank',
    lastName: 'Garcia',
    countryCode: 'US',
    phoneNumber: '5556541239',
    dateOfBirth: new Date('2009-12-12T00:00:00Z'),
    socialSecurity: '876-54-3210',
    identificationType: 2,
    identificationTypeText: 2,
    identificationNumber: 'I9012345',
    createdBy: 'admin',
    createdOn: new Date('2023-09-19T12:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-19T13:00:00Z'),
    isActive: true,
    notes: 'Enjoys history.',
    citizenShip: 'USA',
    gender: 1,
    genderText: 'Male',
    motherName: 'Catherine',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 2,
    religionText: 'Islam',
    placeOfBirth: 'Las Vegas, NV',
    gradeId: 9,
    gradeLabel: '7',
  },
  {
    id: 10,
    firstName: 'Mia',
    middleName: 'Isabella',
    grandParentName: 'Richard',
    lastName: 'Hernandez',
    countryCode: 'US',
    phoneNumber: '5552348765',
    dateOfBirth: new Date('2008-10-23T00:00:00Z'),
    socialSecurity: '543-21-0987',
    identificationType: 1,
    identificationTypeText: 1,
    identificationNumber: 'J0123456',
    createdBy: 'admin',
    createdOn: new Date('2023-09-05T09:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-05T10:00:00Z'),
    isActive: true,
    notes: 'Outstanding in athletics.',
    citizenShip: 'USA',
    gender: 2,
    genderText: 'Female',
    motherName: 'Sophia',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 1,
    religionText: 'Christianity',
    placeOfBirth: 'Orlando, FL',
    gradeId: 10,
    gradeLabel: '8',
  },
  {
    id: 11,
    firstName: 'Lucas',
    middleName: 'Henry',
    grandParentName: 'Peter',
    lastName: 'Lopez',
    countryCode: 'US',
    phoneNumber: '5555674321',
    dateOfBirth: new Date('2006-03-14T00:00:00Z'),
    socialSecurity: '123-45-6789',
    identificationType: 2,
    identificationTypeText: 2,
    identificationNumber: 'K2345678',
    createdBy: 'admin',
    createdOn: new Date('2023-09-17T11:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-17T12:00:00Z'),
    isActive: true,
    notes: 'Good in foreign languages.',
    citizenShip: 'USA',
    gender: 1,
    genderText: 'Male',
    motherName: 'Ana',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 3,
    religionText: 'Islam',
    placeOfBirth: 'San Antonio, TX',
    gradeId: 11,
    gradeLabel: '9',
  },
  {
    id: 12,
    firstName: 'Charlotte',
    middleName: 'Ava',
    grandParentName: 'William',
    lastName: 'Anderson',
    countryCode: 'US',
    phoneNumber: '5554329876',
    dateOfBirth: new Date('2007-04-05T00:00:00Z'),
    socialSecurity: '987-65-4321',
    identificationType: 1,
    identificationTypeText: 1,
    identificationNumber: 'L3456789',
    createdBy: 'admin',
    createdOn: new Date('2023-09-19T14:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-19T15:00:00Z'),
    isActive: true,
    notes: 'Loves public speaking.',
    citizenShip: 'USA',
    gender: 2,
    genderText: 'Female',
    motherName: 'Evelyn',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 2,
    religionText: 'Islam',
    placeOfBirth: 'Dallas, TX',
    gradeId: 12,
    gradeLabel: '10',
  },
  {
    id: 13,
    firstName: 'Benjamin',
    middleName: 'Liam',
    grandParentName: 'James',
    lastName: 'White',
    countryCode: 'US',
    phoneNumber: '5558762341',
    dateOfBirth: new Date('2006-12-25T00:00:00Z'),
    socialSecurity: '456-78-9123',
    identificationType: 2,
    identificationTypeText: 2,
    identificationNumber: 'M4567890',
    createdBy: 'admin',
    createdOn: new Date('2023-09-20T09:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-20T10:00:00Z'),
    isActive: true,
    notes: 'Great team player in sports.',
    citizenShip: 'USA',
    gender: 1,
    genderText: 'Male',
    motherName: 'Lily',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 1,
    religionText: 'Christianity',
    placeOfBirth: 'Denver, CO',
    gradeId: 13,
    gradeLabel: '11',
  },
  {
    id: 14,
    firstName: 'Amelia',
    middleName: 'Chloe',
    grandParentName: 'Oliver',
    lastName: 'Thomas',
    countryCode: 'US',
    phoneNumber: '5559872345',
    dateOfBirth: new Date('2005-09-17T00:00:00Z'),
    socialSecurity: '654-32-1987',
    identificationType: 1,
    identificationTypeText: 1,
    identificationNumber: 'N5678901',
    createdBy: 'admin',
    createdOn: new Date('2023-09-20T11:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-20T12:00:00Z'),
    isActive: true,
    notes: 'Good at mathematics.',
    citizenShip: 'USA',
    gender: 2,
    genderText: 'Female',
    motherName: 'Victoria',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 2,
    religionText: 'Islam',
    placeOfBirth: 'Atlanta, GA',
    gradeId: 14,
    gradeLabel: '12',
  },
  {
    id: 15,
    firstName: 'Alexander',
    middleName: 'John',
    grandParentName: 'Lucas',
    lastName: 'Martinez',
    countryCode: 'US',
    phoneNumber: '5556541987',
    dateOfBirth: new Date('2007-01-10T00:00:00Z'),
    socialSecurity: '321-65-9876',
    identificationType: 1,
    identificationTypeText: 1,
    identificationNumber: 'O6789012',
    createdBy: 'admin',
    createdOn: new Date('2023-09-20T13:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-20T14:00:00Z'),
    isActive: true,
    notes: 'Participates in robotics.',
    citizenShip: 'USA',
    gender: 1,
    genderText: 'Male',
    motherName: 'Ava',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 3,
    religionText: 'Islam',
    placeOfBirth: 'Seattle, WA',
    gradeId: 15,
    gradeLabel: 'PG',
  },
  {
    id: 16,
    firstName: 'Harper',
    middleName: 'Evelyn',
    grandParentName: 'Mason',
    lastName: 'Brown',
    countryCode: 'US',
    phoneNumber: '5553210987',
    dateOfBirth: new Date('2009-08-29T00:00:00Z'),
    socialSecurity: '876-54-3210',
    identificationType: 2,
    identificationTypeText: 2,
    identificationNumber: 'P7890123',
    createdBy: 'admin',
    createdOn: new Date('2023-09-21T09:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-21T10:00:00Z'),
    isActive: true,
    notes: 'Active in debate.',
    citizenShip: 'USA',
    gender: 2,
    genderText: 'Female',
    motherName: 'Mia',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 1,
    religionText: 'Christianity',
    placeOfBirth: 'Portland, OR',
    gradeId: 16,
    gradeLabel: 'KG',
  },
  {
    id: 17,
    firstName: 'Ella',
    middleName: 'Grace',
    grandParentName: 'Ethan',
    lastName: 'Davis',
    countryCode: 'US',
    phoneNumber: '5558762319',
    dateOfBirth: new Date('2008-05-13T00:00:00Z'),
    socialSecurity: '543-21-8765',
    identificationType: 1,
    identificationTypeText: 1,
    identificationNumber: 'Q8901234',
    createdBy: 'admin',
    createdOn: new Date('2023-09-22T11:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-22T12:00:00Z'),
    isActive: true,
    notes: 'Talented in theater.',
    citizenShip: 'USA',
    gender: 2,
    genderText: 'Female',
    motherName: 'Sophia',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 3,
    religionText: 'Islam',
    placeOfBirth: 'San Francisco, CA',
    gradeId: 17,
    gradeLabel: '1',
  },
  {
    id: 18,
    firstName: 'Aiden',
    middleName: 'Landon',
    grandParentName: 'Samuel',
    lastName: 'Rodriguez',
    countryCode: 'US',
    phoneNumber: '5557654321',
    dateOfBirth: new Date('2010-11-21T00:00:00Z'),
    socialSecurity: '432-10-9876',
    identificationType: 2,
    identificationTypeText: 2,
    identificationNumber: 'R9012345',
    createdBy: 'admin',
    createdOn: new Date('2023-09-23T10:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-23T11:00:00Z'),
    isActive: true,
    notes: 'Excels at coding.',
    citizenShip: 'USA',
    gender: 1,
    genderText: 'Male',
    motherName: 'Emily',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 2,
    religionText: 'Islam',
    placeOfBirth: 'Charlotte, NC',
    gradeId: 18,
    gradeLabel: '2',
  },
  {
    id: 19,
    firstName: 'Abigail',
    middleName: 'Lily',
    grandParentName: 'Jacob',
    lastName: 'Gonzalez',
    countryCode: 'US',
    phoneNumber: '5556543219',
    dateOfBirth: new Date('2006-02-02T00:00:00Z'),
    socialSecurity: '109-87-6543',
    identificationType: 1,
    identificationTypeText: 1,
    identificationNumber: 'S0123456',
    createdBy: 'admin',
    createdOn: new Date('2023-09-24T12:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-24T13:00:00Z'),
    isActive: true,
    notes: 'Proficient in painting.',
    citizenShip: 'USA',
    gender: 2,
    genderText: 'Female',
    motherName: 'Isabella',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 1,
    religionText: 'Christianity',
    placeOfBirth: 'Philadelphia, PA',
    gradeId: 19,
    gradeLabel: '3',
  },
  {
    id: 20,
    firstName: 'Elijah',
    middleName: 'Nathan',
    grandParentName: 'Daniel',
    lastName: 'Young',
    countryCode: 'US',
    phoneNumber: '5557651234',
    dateOfBirth: new Date('2008-09-19T00:00:00Z'),
    socialSecurity: '987-65-4321',
    identificationType: 2,
    identificationTypeText: 2,
    identificationNumber: 'T2345678',
    createdBy: 'admin',
    createdOn: new Date('2023-09-25T09:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-25T10:00:00Z'),
    isActive: true,
    notes: 'Great team leader.',
    citizenShip: 'USA',
    gender: 1,
    genderText: 'Male',
    motherName: 'Avery',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 3,
    religionText: 'Islam',
    placeOfBirth: 'Columbus, OH',
    gradeId: 20,
    gradeLabel: '4',
  },
  {
    id: 21,
    firstName: 'Scarlett',
    middleName: 'Zoe',
    grandParentName: 'Benjamin',
    lastName: 'Hall',
    countryCode: 'US',
    phoneNumber: '5551230987',
    dateOfBirth: new Date('2010-12-11T00:00:00Z'),
    socialSecurity: '543-21-8765',
    identificationType: 1,
    identificationTypeText: 1,
    identificationNumber: 'U3456789',
    createdBy: 'admin',
    createdOn: new Date('2023-09-26T11:00:00Z'),
    updatedBy: 'admin',
    updatedOn: new Date('2023-09-26T12:00:00Z'),
    isActive: true,
    notes: 'Strong in mathematics.',
    citizenShip: 'USA',
    gender: 2,
    genderText: 'Female',
    motherName: 'Mila',
    maritalStatus: 1,
    maritalStatusText: 'Single',
    religion: 1,
    religionText: 'Christianity',
    placeOfBirth: 'Indianapolis, IN',
    gradeId: 21,
    gradeLabel: '5',
  },
];
